# Generated by Django 5.0.7 on 2024-07-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busNo', models.TextField(max_length=255)),
                ('driverName', models.TextField()),
                ('driverContact', models.PositiveBigIntegerField()),
                ('busRoute', models.TextField()),
            ],
        ),
    ]
