# Generated by Django 5.0.7 on 2024-07-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busroutings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studentinfo',
            fields=[
                ('collegeid', models.IntegerField(db_column='collegeID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('branch', models.CharField(blank=True, max_length=50, null=True)),
                ('collegename', models.CharField(blank=True, db_column='collegeName', max_length=50, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('busno', models.IntegerField(blank=True, db_column='busNo', null=True)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('emailid', models.CharField(blank=True, db_column='emailID', max_length=60, null=True)),
                ('password', models.CharField(blank=True, max_length=30, null=True)),
                ('boardingpt', models.CharField(blank=True, db_column='boardingPt', max_length=40, null=True)),
            ],
        ),
    ]
