# Generated by Django 5.0.7 on 2024-07-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busroutings', '0003_alter_studentinfo_busno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='busno',
            field=models.CharField(blank=True, db_column='busNo', max_length=20, null=True),
        ),
    ]
